### PR TITLE
Use keyType during key generation to create correct key type

### PR DESCRIPTION
**Pull request by afitzek**
Change-Type: patch
Connects-To: #27
Signed-off-by: Andreas Fitzek <andreas@resin.io>
---- Autogenerated Waffleboard Connection: Connects to #27

### CODE REVIEW

**Comment by wrboyce** [comment]
That is unfortunate, it looks like the lint has been updated since the last build.

**Comment by afitzek** [comment]
No worries I fixed that as well. :)

**Comment by afitzek** [comment]
@wrboyce Sure thing. I just copy/pasted the `versionist.conf.js` from the link. Let me know if this is correct.

**Comment by wrboyce** [comment]
Looks good, thanks @afitzek!

**Pull request merged**
