### PR TITLE
Remove debug code from Makefile

### LINKED ISSUE #16: Needs CI integration / Dockerfile-based build workflow

### PR DESCRIPTION
**Pull request by wrboyce**
Fixes #16
Change-Type: patch

### CODE REVIEW

**Comment by wrboyce** [comment]
@lekkas can you give this a quick approval please? There were some leftover `echo` statements in the Makefile blocking the release upload!

**Comment by wrboyce** [comment]
Thanks @lekkas, now (hopefully!) releases should get automatically built and pushed up to GitHub.

**Comment by wrboyce** [comment]
[It worked](https://github.com/resin-io/sshproxy/releases/tag/v1.2.1)!

**Comment by lekkas** [comment]
Circle building uploading artifacts and checksums - This is pretty cool, nice work @wrboyce :)

**Comment by lekkas** [comment]
The only change we may have to do in the future is replace the storage with an resin.io s3 AWS bucket, but release notes + checksums will remain in any case

**Pull request merged**
